### ISSUE TITLE
Version 0.1.0 roadmap

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/DemoCards.jl#1]
This package is developed to replace the current demo page of https://juliaimages.org/latest/demos/

The "new" demo page is expected to be:

* easy to deploy; seamlessly integrate with [`Documenter.jl`](https://github.com/JuliaDocs/Documenter.jl) and [`Literate.jl`](https://github.com/fredrikekre/Literate.jl)
* easy to write; demo authors (not necessary package maintainers) only need to provide a single file (with assets) with no need to understand the entire documentation mechanism.
* CI supported; 

Roadmap:

* functionalities
  - [x] decouple {demo_image}, {demo_title} and {demo_file}; currently they're of the same name.
  - [ ] integrate with `Literate.jl` to support CI
  - [x] provide a default style sheet
* beautify the demo page
  - [x] custom sections and cards order; currently it's sorted alphabetically.
  - [x] make a grid of demo cards; currently it's listed vertically.
* nice to have:
  - [x] multiple demo pages
  - [x] simplify the card template

**Comment by johnnychen94** [comment]
Although there're many details needed to be checked and fixed, this package is now ready to be tested by other packages.

I'd like to fully test the markdown features first, and then consider the integration with `Literate.jl`.
